# Generated by Django 2.2.5 on 2019-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='images/books/')),
                ('title', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=8)),
            ],
        ),
    ]
