# Generated by Django 2.2.5 on 2019-10-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='title',
            new_name='name',
        ),
    ]
