# Generated by Django 2.2.5 on 2019-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191001_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='books/images'),
        ),
    ]
