# Generated by Django 2.2.5 on 2019-10-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_ad_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='id',
        ),
        migrations.AddField(
            model_name='ad',
            name='product_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
