# Generated by Django 2.2.5 on 2019-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191002_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='product_id',
        ),
        migrations.AddField(
            model_name='ad',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
