# Generated by Django 2.2.5 on 2019-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191002_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
