# Generated by Django 2.2.5 on 2019-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191002_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_no',
            field=models.CharField(default='', max_length=14),
        ),
    ]
