# Generated by Django 2.2.5 on 2019-10-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191002_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='owner',
            field=models.CharField(default='Annoymus', max_length=30),
        ),
    ]
