# Generated by Django 2.2.5 on 2019-10-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20191015_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
