# Generated by Django 2.2.5 on 2019-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_ad_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Abhishek', max_length=20)),
            ],
        ),
    ]
